import Head from "next/head";
import Header from "../components/Header";
import MainPage from "../components/MainPage";
import { client } from "../utils/client";

export default function Home({data}) {
  
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <MainPage data={data}/>
    </div>
  );
}


export const getServerSideProps = async () => {
  const query = `*[_type == "post"] | order(_createdAt desc){
    _id,
     caption,
     _updatedAt,
       video{
        asset->{
          _id,
          url
        }
      },
      userId,
      postedBy->{
        _id,
        userName,
        image,
        email,
        userId
      },
    }`;

  const res = await client.fetch(query);
  return {
    props: {
      data:res,
    },
  };
};
